import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import Fotter from "./components/fotter";



export const metadata: Metadata = {
  title: "rerereSuperGirl",
  description: "Generated by create my-blog",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="font-sans">
        <Header />
            {children}
        <Fotter />
      </body>
    </html>
  );
}
